var EVENT_COMMIT_GAME = 'event_commit_game';
var REFRESH_TIME_OUT = 60000;
var VIEW_REFRESH_TIME_OUT = 20;
var SLOW_COUNT = 10;
var ENEMY_SPEED = 2;
var ENEMY_INDEX_BLOCK= 40;
var ENEMY_LAZY = (1000/VIEW_REFRESH_TIME_OUT);
var ENEMY_LAZY_INTERLEAVE = 50;
var BULLET_SPEED = 5;

var PROXY_EVENT_UPDATE = 'proxy_update';

var PROXY_NAME_PLAYER  = 'proxy_player';
var PROXY_NAME_GAME = 'proxy_game';
var PROXY_NAME_SCENARIO = 'proxy_scenario';
var PROXY_NAME_DEFENDER = 'proxy_defender';


var MAP_NOTHING = 0;
var MAP_PASS_ROAD   = 1;
var MAP_DOWN   = 2;
var MAP_UP     = 4;
var MAP_LEFT   = 8;
var MAP_RIGHT  = 16;
var MAP_START  = 32;
var MAP_FINISH = 64;
var MAP_DEFENDABLE = 128;


var MEDIATOR_NAME_BACKGROUND = 'mediator_background';
var MEDIATOR_NAME_ENEMIES = 'mediator_enemies';
var MEDIATOR_NAME_GAMEVIEW = 'mediator_gameview';
var MEDIATOR_NAME_BATTLEVIEW = 'mediator_battleview';
var MEDIATOR_NAME_TOWERVIEW = 'mediator_towerview';
var MEDIATOR_NAME_BULLETVIEW = 'mediator_bulletview';

var COMMAND_NAME_START = 'command_name_start';
var COMMAND_NAME_PLAY = 'command_name_play';
var COMMAND_NAME_PLAY_SNAPSHOT = 'command_name_play_snapshot';
var COMMAND_NAME_COMMIT = 'command_name_commit';
var COMMAND_NAME_REFRESH = 'command_name_refresh';
var COMMAND_NAME_EMBATTLE = 'command_name_embattle';
var COMMAND_NAME_REMOVE_DEFENDER = 'command_name_remove_defender';
var COMMAND_NAME_UPGRADE_DEFENDER = 'command_name_upgrade_defender';

var COMMAND_EVENT_START = 'command_event_start';
var COMMAND_EVENT_PLAY = 'command_event_play';
var COMMAND_EVENT_PLAY_SNAPSHOT = 'command_event_play_snapshot';
var COMMAND_EVENT_COMMIT = 'command_event_commit';
var COMMAND_EVENT_COMMIT_ACK = 'command_event_commit_ack';
var COMMAND_EVENT_REFRESH = 'command_event_refresh';
var COMMAND_EVENT_EMBATTLE = 'command_event_embattle';
var COMMAND_EVENT_EMBATTLE_ACK = 'command_event_embattle_ack';
var COMMAND_EVENT_REMOVE_DEFENDER = 'command_event_remove_defender';
var COMMAND_EVENT_REMOVE_DEFENDER_ACK = 'command_event_remove_defender_ack';
var COMMAND_EVENT_UPGRADE_DEFENDER = 'command_event_upgrade_defender';
var COMMAND_EVENT_UPGRADE_DEFENDER_ACK = 'command_event_upgrade_defender_ack';

var SCENARIO_MAP = [];
SCENARIO_MAP.push([
        [MAP_NOTHING, MAP_START + MAP_RIGHT, MAP_NOTHING, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_NOTHING],  
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DOWN, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_FINISH + MAP_DOWN],  
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_NOTHING], 
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],                                                                                        
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DOWN, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_LEFT, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE]
        ]); 


SCENARIO_MAP.push([
        [MAP_NOTHING, MAP_NOTHING, MAP_START + MAP_RIGHT, MAP_NOTHING, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_NOTHING],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DOWN, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_FINISH + MAP_DOWN],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_NOTHING], 
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],                                                                                        
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DOWN, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_LEFT, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE]
        ]); 

var TOWER_TYPES = [
{name: 'tower_0', id: 0, life: 100, cost: 50, speed: 2, cold: 100, damage: 20, scope: 50, burst: 1, slow: 0, steal: 0, bulletID: 1, bulletScope: 0, bulletSpeed: 5},
{name: 'tower_1', id: 1, life: 150, cost: 100, speed: 2, cold: 100, damage: 30, scope: 70, burst: 1, slow: 0, steal: 0, bulletID: 2, bulletScope: 0, bulletSpeed: 5}
];

var ENEMY_TYPES = [
{name: 'enemy_0', id: 0, life: 100, cost: 50, speed: 2, cold: 100, damage: 20, scope: 50, burst: 1, slow: 0, steal: 0, bulletID: 1, bulletScope: 0, bulletSpeed: 5},
{name: 'enemy_1', id: 1, life: 150, cost: 100, speed: 2, cold: 100, damage: 30, scope: 70, burst: 1, slow: 0, steal: 0, bulletID: 2, bulletScope: 0, bulletSpeed: 5}
];

