var REFRESH_TIME_OUT = 60000;
var VIEW_REFRESH_TIME_OUT = 20;
var ENEMY_SLOW_COUNT = 10;
var ENEMY_INDEX_BLOCK= 40;
var ENEMY_IMAGE_BLOCK_SIZE = 40;
var TOWER_IMAGE_BLOCK_SIZE = 50;
var BULLET_IMAGE_BLOCK_SIZE = 50;
var BUTTON_IMAGE_BLOCK_SIZE = 50;
var ENEMY_LAZY = (1000/VIEW_REFRESH_TIME_OUT);
var ENEMY_LAZY_INTERLEAVE = 50;
var BULLET_SPEED = 5;
var UPGRADE_COST_RATIO = 1/4;
var INIT_LIFE = 10;

var PROXY_EVENT_UPDATE = 'proxy_update';

var PROXY_NAME_PLAYER  = 'proxy_player';
var PROXY_NAME_GAME = 'proxy_game';
var PROXY_NAME_SCENARIO = 'proxy_scenario';
var PROXY_NAME_DEFENDER = 'proxy_defender';


var MAP_NOTHING = 0;
var MAP_PASS_ROAD   = 1;
var MAP_DOWN   = 2;
var MAP_UP     = 4;
var MAP_LEFT   = 8;
var MAP_RIGHT  = 16;
var MAP_START  = 32;
var MAP_FINISH = 64;
var MAP_DEFENDABLE = 128;

var MAP_BLOCK_SIZE = 50;
var CONTROL_BLANK_WIDTH = 20;


var MEDIATOR_NAME_BACKGROUND = 'mediator_background';
var MEDIATOR_NAME_BATTLE = 'mediator_battle';
var MEDIATOR_NAME_TOWER = 'mediator_tower';
var MEDIATOR_NAME_PLAN = 'mediator_plan';
var MEDIATOR_NAME_CONTROL = 'mediator_control';

var COMMAND_NAME_START = 'command_name_start';
var COMMAND_NAME_PLAY = 'command_name_play';
var COMMAND_NAME_PLAY_SNAPSHOT = 'command_name_play_snapshot';
var COMMAND_NAME_COMMIT = 'command_name_commit';
var COMMAND_NAME_REFRESH = 'command_name_refresh';
var COMMAND_NAME_EMBATTLE = 'command_name_embattle';
var COMMAND_NAME_UNEMBATTLE = 'command_name_unembattle';
var COMMAND_NAME_UPGRADE = 'command_name_upgrade';

var EVENT_START = 'event_start';
var EVENT_PLAY = 'event_play';
var EVENT_PLAY_SNAPSHOT = 'event_play_snapshot';
var EVENT_COMMIT_WAVE = 'event_commit_wave';
var EVENT_COMMIT_WAVE_ACK = 'event_commit_wave_ack';
var EVENT_COMMIT_GAME = 'event_commit_game';
var EVENT_COMMIT_GAME_ACK = 'event_commit_game_ack';
var EVENT_REFRESH = 'event_refresh';
var EVENT_EMBATTLE = 'event_embattle';
var EVENT_EMBATTLE_ACK = 'event_embattle_ack';
var EVENT_UNEMBATTLE = 'event_unembattle';
var EVENT_UNEMBATTLE_ACK = 'event_unembattle_ack';
var EVENT_UPGRADE = 'event_upgrade';
var EVENT_UPGRADE_ACK = 'event_upgrade_ack';

var SCENARIO_MAP = [];
SCENARIO_MAP.push([
        [MAP_NOTHING, MAP_START + MAP_RIGHT, MAP_NOTHING, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_NOTHING],  
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DOWN, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_FINISH + MAP_DOWN],  
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_NOTHING], 
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],                                                                                        
        [MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DOWN, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_LEFT, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE]
        ]); 


SCENARIO_MAP.push([
        [MAP_NOTHING, MAP_NOTHING, MAP_START + MAP_RIGHT, MAP_NOTHING, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_NOTHING],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DOWN, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_FINISH + MAP_DOWN],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_NOTHING], 
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],                                                                                        
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_PASS_ROAD, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DOWN, MAP_PASS_ROAD, MAP_PASS_ROAD, MAP_LEFT, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE],  
        [MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE, MAP_DEFENDABLE]
        ]); 

var PLAYER_INIT_MONEY = 1000;

var TOWER_TYPES = [
{name: 'tower_0', id: 0, life: 100, cost: 50, speed: 2, cold: 100, damage: 20, scope: 50, burst: 1, slow: 0, steal: 0, bulletID: 1, bulletScope: 0, bulletSpeed: 5},
{name: 'tower_1', id: 1, life: 150, cost: 100, speed: 2, cold: 100, damage: 30, scope: 70, burst: 1, slow: 0, steal: 0, bulletID: 2, bulletScope: 0, bulletSpeed: 5}
];

var ENEMY_TYPES = [
{name: 'enemy_0', id: 0, life: 100, cost: 50, speed: 10, cold: 100, damage: 20, scope: 50, burst: 1, slow: 0, steal: 0, bulletID: 1, bulletScope: 0, bulletSpeed: 5},
{name: 'enemy_1', id: 1, life: 150, cost: 100, speed: 2, cold: 100, damage: 30, scope: 70, burst: 1, slow: 0, steal: 0, bulletID: 2, bulletScope: 0, bulletSpeed: 5}
];

